-- AlterEnum
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'ROSTER_IMPORTED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'ROSTER_ASSIGNED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'ROSTER_REASSIGNED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'ROSTER_UNASSIGNED';

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneE164" TEXT;
