ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'QR_CREATED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'QR_STATUS_UPDATED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'QR_DELETED';

ALTER TABLE "QRCode"
  ADD COLUMN IF NOT EXISTS "qrImageUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "QRCode_eventId_deletedAt_idx" ON "QRCode"("eventId", "deletedAt");
