ALTER TABLE "Team"
ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Team_eventId_deletedAt_idx"
  ON "Team"("eventId", "deletedAt");

ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'TEAM_SCORE_UPDATED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'TEAM_SOFT_DELETED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'PLAYER_CONTACT_UPDATED';
